version: '3.8'
services:
  chatbot:
    image: 635773515765.dkr.ecr.ap-southeast-2.amazonaws.com/apra-amcos-chatbot-sagemaker-poc 
    ports:
      - "5000:8080"
    platform: linux/amd64
    environment:
      PINECONE_API_KEY: <your_pinecone_key>
      OPENAI_API_KEY: <your_openAI_key>
      AWS_REGION: "ap-southeast-2"
      AWS_ACCESS_KEY_ID: <only_for_local_docker>
      AWS_SECRET_ACCESS_KEY: <only_for_local_docker>
      AWS_SESSION_TOKEN: <only_for_local_docker>
      
